### ISSUE TITLE
Error "Value of [Setup] section directive "OutputBaseFileName" is invalid."

### ISSUE THREAD

**Issue by elendil-software** [Minionguyjpro/Inno-Setup-Action#126]
Hi,

When 

```yaml
- name: Compile .ISS to .EXE Installer
  if: ${{ inputs.build_installer == true }}
  uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
  with:
    path: Output\InnoSetup\Setup.iss
    options: /Dversion=${{ steps.gitversion.outputs.MajorMinorPatch }} /DVersionInfoVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}
```

which result in 

```yaml
Run Minionguyjpro/Inno-Setup-Action@v1.2.7
  with:
    path: Output\InnoSetup\Setup.iss
    options: /Dversion=0.1.0 /DVersionInfoVersion=0.1.0
  env:
     ...
```

I get the error

> Error: Execution failed: Error on line 23 in D:\a\RefractionMeteoFileUpdater\RefractionMeteoFileUpdater\Output\InnoSetup\Setup.iss: Value of [Setup] section directive "OutputBaseFileName" is invalid.

Line 23 is

> OutputBaseFilename=Refraction Meteo File Updater Setup v{#version}

and version is passed as parameter and a fallback value is defined at the begining of the script with 

```
#ifndef version
  #define version "0.9.0"
#endif
```

This script works locally and when calling Inno Setup installed in action runner up to windows server 2022 (removed in windows server 2025)

**Comment by Minionguyjpro** [comment]
> > So basically you're saying that it works on Server 2022 images but not on 2025 images?
> 
> Yes.
> 
> If this may help I can try without the {#version} variable to see if this change anything

Try that, I might have some parsing issues when it comes to those in my code.

**Comment by Minionguyjpro** [comment]
Could you try running the action off the main branch right now? I pushed a commit that swapped the orders of the arguments passed to the Inno Setup (before was arguments first and then script, now it's first the script and then other arguments) that might fix it.

**Comment by elendil-software** [comment]
Still doesn't work :

> Error: Execution failed: Error on line 23 in D:\a\RefractionMeteoFileUpdater\RefractionMeteoFileUpdater\Output\InnoSetup\Setup.iss: Value of [Setup] section directive "OutputBaseFileName" is invalid.

If this can help, I can make my repository public, there is nothing secret in there. So you can fork it and try on it.

**Comment by elendil-software** [comment]
@Minionguyjpro 
Did you have the time to check this issue ?

**Comment by ximion** [comment]
I am also affected by this, but for me the issue appeared when Dependabot suggested upgrading the Action from `Minionguyjpro/Inno-Setup-Action@v1.2.2` to `Minionguyjpro/Inno-Setup-Action@v1.2.7`.

With `1.2.2` I do not get this issue at all and builds work fine, with `1.2.7` builds fail. I also have a `#define` in my `OutputBaseFilename` that is defined as a parameter of the action. The value of `OutputBaseFilename` is `MyApp-{#AppVersion}_Setup_win64`.

**Comment by barasimumatik** [comment]
So this will be a long comment, because I bashed my head against this for way too long and need to vent 😅

It looks like the switch from `exec` to `execFile` (i.e. one of the changes between 1.2.5 and 1.2.6) causes the issue.

With `exec` the command is passed together with the arguments in one string like so

`exec("command.exe arg1 arg2 arg3", ...other exec options)`  (which evaluates to `command.exe arg1 arg2 arg3`)

With `execFile`, the options are passed separately as an array of strings:

`execFile("command.exe", ["arg1", "arg2", "arg3"], ... other execFile options)` (which also evaluates to `command.exe arg1 arg2 arg3`)

With the following workflow step

<pre>
- name: Compile .ISS to .EXE Installer
  if: ${{ inputs.build_installer == true }}
  uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
  with:
    path: setup.iss
    options: arg1 arg2 arg3
</pre>

each action input is passed in an environment variable where the name is the name of the action input in upper case + the prefix `INPUT_`. E.g. `INPUT_PATH=setup.iss` and `INPUT_OPTIONS="arg1 arg2 arg3"`. 

In v1.2.5, the action reads the INPUT_OPTIONS with getInput which will simply return the string "arg1 arg2 arg3", so the exec call evaluates to `iscc.exe setup.iss arg1 arg2 arg3` as expected. 

In v1.2.6 the action reads the INPUT_OPTIONS with getMultilineInput which reads an input, splits it by newlines and trims the whitespaces from each element. The execFile call evaluates to `iscc.exe setup.iss "arg1 arg2 arg3"`. 

I don't know if Inno Setup ignores invalid arguments like that or not, but either way, this doesn't seem to work.

I experimented with different variants of YAML string formats and found two workarounds for v1.2.6+ that seem to work (by adding the right amount of newlines). 

**First:** 

<pre>
- name: Compile .ISS to .EXE Installer
  if: ${{ inputs.build_installer == true }}
  uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
  with:
    path: setup.iss
    options: "arg1 \narg2  \narg3"
</pre>

Which results in the getMultilineInput returning an array with three elements:  `["arg1", "arg2", "arg3"]`.

**Second:**

<pre>
- name: Compile .ISS to .EXE Installer
  if: ${{ inputs.build_installer == true }}
  uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
  with:
    path: setup.iss
    options: |-
      arg1 
      arg2 
      arg3
</pre>

The `|-` block scalar format keeps newlines between the lines, ignores leading whitespaces and strips the last newline (the other variants `|` and `|+`  handles newlines differently and will not work). This should be equivalent to the first version (i.e. a single string with newlines between the parts).

So in this case I think this should work:

<pre>
- name: Compile .ISS to .EXE Installer
  if: ${{ inputs.build_installer == true }}
  uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
  with:
    path: Output\InnoSetup\Setup.iss
    options: |-
      /Dversion=${{ steps.gitversion.outputs.MajorMinorPatch }} 
      /DVersionInfoVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}
</pre>

Pro tip: https://yaml-multiline.info/

**Comment by elendil-software** [comment]
@barasimumatik 
It works !
Many, many thanks ! 👍🏻 🥇
